# Generated by Django 6.0.6 on 2026-06-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moment',
            field=models.CharField(blank=True, help_text='The moment this candle preserves, e.g. "Sunday mornings with nowhere to be"', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='notes_base',
            field=models.CharField(blank=True, help_text='Base / dry-down notes', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='notes_heart',
            field=models.CharField(blank=True, help_text='Heart / middle notes', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='notes_top',
            field=models.CharField(blank=True, help_text='Top / opening notes', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='ritual',
            field=models.TextField(blank=True, help_text='How to enjoy it — the lighting ritual'),
        ),
        migrations.AddField(
            model_name='product',
            name='story',
            field=models.TextField(blank=True, help_text='The narrative / inspiration behind this candle'),
        ),
    ]
