# Generated by Django 6.0.6 on 2026-06-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_moment_product_notes_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='story',
            field=models.TextField(blank=True, help_text='The narrative behind this collection'),
        ),
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.CharField(blank=True, help_text='A short, evocative line for the collection', max_length=200),
        ),
    ]
