# Generated by Django 6.0.6 on 2026-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
