# Generated by Django 6.0.6 on 2026-06-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cod_enabled',
            field=models.BooleanField(default=True, help_text='Allow Cash on Delivery at checkout'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='flat_shipping_rate',
            field=models.DecimalField(decimal_places=2, default=49, help_text='Shipping charge below the free-shipping threshold', max_digits=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='prices_include_tax',
            field=models.BooleanField(default=True, help_text='If on, displayed prices already include tax (a note is shown). If off, tax is added at checkout.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tax_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tax_label',
            field=models.CharField(default='GST', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='e.g. 18 for 18%', max_digits=5),
        ),
    ]
