# Generated by Django 6.0.6 on 2026-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=300)),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=50)),
                ('background_color', models.CharField(default='#C9A86A', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(choices=[('hero', 'Hero Banner'), ('home_featured', 'Home Featured'), ('sidebar', 'Sidebar'), ('popup', 'Popup'), ('announcement', 'Announcement Bar')], default='hero', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('background_color', models.CharField(blank=True, max_length=20)),
                ('text_color', models.CharField(blank=True, max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['position', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('page_type', models.CharField(choices=[('about', 'About'), ('contact', 'Contact'), ('faq', 'FAQ'), ('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('refund', 'Refund Policy'), ('shipping', 'Shipping Policy'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True)),
                ('show_in_header', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='popups/')),
                ('trigger', models.CharField(choices=[('on_load', 'On Page Load'), ('exit_intent', 'Exit Intent'), ('time_delay', 'Time Delay')], default='time_delay', max_length=20)),
                ('delay_seconds', models.PositiveIntegerField(default=5)),
                ('show_once', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('show_on_pages', models.CharField(blank=True, help_text='Comma-separated page slugs, leave blank for all pages', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
