# Generated by Django 5.0.6 on 2026-06-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('review_approved', 'Review Approved'), ('wishlist_back_in_stock', 'Back in Stock'), ('admin_new_order', 'Admin New Order'), ('system', 'System')], max_length=30),
        ),
    ]
